app/models/__init__.py
#!/usr/bin/env python
# coding: utf-8

from .user import User

app/models/chathistory.py
#!/usr/bin/env python
# coding: utf-8

from datetime import datetime
from app import db


class ChatHistory(db.Model):
    __tablename__ = 'chat_histories'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, index=True)
    bot_type_str = db.Column(db.String(36))  # 模型类型，确定之后不能改变
    session_id = db.Column(db.String(36))  # Assuming UUID is used for session_id
    message = db.Column(db.Text)
    sender = db.Column(db.String(10))  # Assuming 'system', 'user' or 'bot' as possible values
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)

    def save_message(self):
        db.session.add(self)
        db.session.commit()

app/models/payment.py
from datetime import datetime
from app import db


class Payment(db.Model):
    __tablename__ = 'payments'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    amount = db.Column(db.Float)
    count = db.Column(db.Integer)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)

    def create_payment(self):
        db.session.add(self)
        db.session.commit()

app/models/user.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from app import db


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    verified = db.Column(db.Boolean, default=False)
    remaining_count = db.Column(db.Integer, default=10)
    name = db.Column(db.String(64))

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        print('password:', password)
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    # @login_manager.user_loader
    # def load_user(self, user_id):
    #     return User.query.get(int(user_id))

    def get_by_email(self, email):
        return self.query.filter_by(email=email).first()

    def create_user(self):
        if not self.get_by_email(self.email):
            db.session.add(self)
            db.session.commit()
            return True
        return False

    def verify_email(self):
        self.verified = True
        db.session.commit()

    def update_remaining_count(self, count):
        self.remaining_count = count
        db.session.commit()

    def update_name(self, name):
        self.name = name
        db.session.commit()

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

import os

db = SQLAlchemy()
login_manager = LoginManager()
migrate = Migrate()
chat_histories = {}


def create_app():
    app = Flask(__name__)
    base_dir = os.path.abspath(os.path.dirname(__file__))  # 获取项目的根目录的绝对路径
    database_path = os.path.join(base_dir, 'database')
    if not os.path.exists(database_path):
        os.makedirs(database_path)

    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(base_dir, 'database/database.db')
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    app.config['SECRET_KEY'] = 'your-secret-key-hh11'  # replace 'your-secret-key' with your own secret key

    db.init_app(app)
    login_manager.init_app(app)

    # migrate.init_app(app, db)

    @login_manager.user_loader
    def load_user(user_id):
        from app.models import User
        return User.query.get(int(user_id))

    from app.models import User
    from app.routes import auth

    import app.view as view
    app.register_blueprint(view.main)
    import app.routes.auth as auth
    app.register_blueprint(auth.auth)

    import app.routes.mychatgpt as mychatgpt
    app.register_blueprint(mychatgpt.chat)

    return app

app/routes/auth.py
from flask import Blueprint, request, render_template, flash, redirect, url_for,current_app
from flask_login import login_user, logout_user, login_required
from app.models import User

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        user = User.query.filter_by(email=request.form['email']).first()
        if user is not None and user.verify_password(request.form['password']):
            login_user(user)
            return redirect(request.args.get('next') or url_for('main.index'))
        flash('Invalid username or password.')
    return render_template('login.html')


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('main.index'))


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')
        password_confirm = request.form.get('confirm_password')
        print(username, email, password, password_confirm)
        # 在这里，你需要验证用户输入，比如检查两次密码输入是否一致
        if password != password_confirm:
            return "Passwords do not match.", 400
        # 然后，尝试创建新用户并保存到数据库中
        new_user = User(name=username, email=email)
        new_user.password = password  # 使用 User 模型中的 password 属性
        if new_user.create_user():  # 使用 User 模型中的 create_user() 方法
            # 如果用户创建成功，重定向用户到登录页面
            return redirect(url_for('auth.login'))
        else:
            # 如果用户创建失败（可能是因为邮箱已被注册），可以返回一个错误信息
            return "Email already registered.", 400
    return render_template('signup.html')  # 如果是GET请求，直接显示注册页面

app/routes/mychatgpt.py
#!/usr/bin/env python
# coding: utf-8
from uuid import uuid4

from flask import Blueprint, request, render_template, flash, redirect, url_for

from flask import g, jsonify
from threading import Lock

from flask_login import login_required, current_user
from app import chat_histories
from langchain.chat_models import ChatOpenAI
from langchain.schema import (
    AIMessage,
    HumanMessage,
    SystemMessage
)
import os
from dotenv import load_dotenv, find_dotenv

_ = load_dotenv(find_dotenv())


chat = Blueprint('chat', __name__)


@chat.before_request
def before_request():
    if 'locks' not in g:
        g.locks = {}


@chat.route('/chat/get_msg', methods=['GET', 'POST'])
@login_required
def get_msg():
    # 登录校验
    if current_user.is_authenticated is False:
        return redirect(url_for('auth.login'))
    # 剩余次数校验
    if current_user.remaining_count <= -10000:
        return jsonify({
            'message': f"你当前剩余次数为{current_user.remaining_count}，请购买更多次数。"
        })
    email = current_user.email
    if email not in g.locks:
        g.locks[email] = Lock()

    lock = g.locks[email]

    if lock.locked():
        return {"error": "Another request is being processed."}, 429

    # Add lock to prevent multiple requests from the same user.
    with lock:
        bot_type_str = 'gpt-3.5-turbo'
        message = request.json.get('message')
        session_id = request.json.get('session_id')

        # If session_id is not provided or not found in chat_histories,
        # create a new session.
        if not session_id or session_id not in chat_histories:
            session_id = str(uuid4())
            chat_histories[session_id] = []
        # Add user's message to chat history.
        chat_histories[session_id].append(HumanMessage(content=message))

        # TODO: Send message to langchain API and get model's reply.
        # reply = ...
        msgs = chat_histories[session_id]
        chat_ai = ChatOpenAI(temperature=0.5,
                             openai_api_key=os.getenv("OPENAI_API_KEY"),
                             openai_api_base='https://api.openai-proxy.com/v1')
        reply = chat_ai(msgs)
        print(reply.content)
        current_user.remaining_count -= 1
        current_user.update_remaining_count(current_user.remaining_count)
        print(current_user.remaining_count)
        # Add model's reply to chat history.
        chat_histories[session_id].append(AIMessage(content=reply.content))

    return jsonify({
        'session_id': session_id,
        'message': reply.content
    })

app/templates/app.html
<!DOCTYPE html>
<html lang="zh">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>实验样式</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js"></script>
  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<!--  <script src="https://cdn.jsdelivr.net/npm/marked/lib/marked.umd.js"></script>-->
<!--  <script src="https://cdn.jsdelivr.net/npm/marked-highlight/lib/index.umd.js"></script>-->
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
  <style>
        html, body {
            height: 100%;
        }
        #display-window {
            height: calc(100% - 112px);
            overflow-y: scroll;
        }
        .message {
            margin-bottom: 1em;
        }
    </style>
</head>
<body class="d-flex flex-column">
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">样式测试</a>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">角色扮演</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">编程助手</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">情感专家</a>
      </li>
    </ul>
    <div class="navbar-text">
      {% if current_user.is_authenticated %}
      {{ current_user.email }} 剩余次数: {{ current_user.remaining_count }}
      <a href="{{ url_for('auth.logout') }}">登出</a>
      {% else %}
      请登录 <a href="{{ url_for('auth.login') }}">登录</a>
      {% endif %}
    </div>
  </div>
</nav>

<!-- Rich text display window -->
<!-- Rich text display window -->
<div class="container mt-4 flex-grow-1">
  <div class="card h-100">
    <div class="card-body" id="display-window">
      <!-- Text, code, LaTeX formulas, etc. will be displayed here -->
      <div class="message text-right">
        <div class="d-flex align-items-start justify-content-end">
        <div class="bg-primary text-white p-3 rounded">
          从1加到10，请用LaTeX格式展示.
        </div>
        <img src="https://plus.unsplash.com/premium_photo-1683865775631-3283bfaf6508?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGF2YXRhcnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60" alt="User Avatar" width="40" height="40" class="rounded-circle ml-2">
      </div>
        </div>
      <div class="message">
        <div class="d-flex align-items-start">
        <img src="https://plus.unsplash.com/premium_photo-1683690944936-18103fa341dd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1100&q=80" alt="Model Avatar" width="40" height="40" class="rounded-circle mr-2">
        <div class="bg-light p-3 rounded">
          Sure, the sum of an arithmetic series can be found with the formula:
          <br>
          <!-- Note: In reality, you would use a library like MathJax to render this formula. -->
          \( S = \frac{n}{2}(a + l) \)
          <br>
          Where:
          <br>
          \( n \) is the number of terms (10 in this case),
          <br>
          \( a \) is the first term (1 in this case),
          <br>
          \( l \) is the last term (10 in this case).
        </div>
      </div>
      </div>

      <div class="message text-right">
        <div class="d-flex align-items-start justify-content-end">

        <div class="bg-primary text-white p-3 rounded">
          用python编写一个函数，实现从1到10.
        </div>
        <img src="https://plus.unsplash.com/premium_photo-1683865775631-3283bfaf6508?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGF2YXRhcnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60" alt="User Avatar" width="40" height="40" class="rounded-circle ml-2">
      </div>
        </div>
      <div class="message">
        <div class="d-flex align-items-start">

        <img src="https://plus.unsplash.com/premium_photo-1683690944936-18103fa341dd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1100&q=80" alt="Model Avatar" width="40" height="40" class="rounded-circle mr-2">
        <div class="bg-light p-3 rounded">
          <!-- Code block -->
          <pre><code class="language-python">
def sum_from_1_to_n(n):
    return (n / 2) * (1 + n)

print(sum_from_1_to_n(10))
          </code></pre>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>


<!-- Input field and Send button -->
<div class="container mt-4">
  <div class="input-group">
    <input type="text" class="form-control" id="user-input" placeholder="Type a message...">
    <!-- Send button -->
    <div class="input-group-append">
      <button class="btn btn-outline-secondary" id="send-button" type="button">Send</button>
    </div>
  </div>
</div>
<script src="{{ url_for('static', filename='chat_box.js') }}"></script>
<script src="{{ url_for('static', filename='send.js') }}"></script>
<script>
document.addEventListener('DOMContentLoaded', (event) => {
    hljs.highlightAll();
});


</script>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
</head>
<body>
<div class="container">
  <h2 class="text-center">登录</h2>
  <form action="{{ url_for('auth.login') }}" method="post">
    <div class="form-group">
      <label for="username">邮箱:</label>
      <input type="text" class="form-control" id="username" name="email" required>
    </div>
    <div class="form-group">
      <label for="pwd">密码:</label>
      <input type="password" class="form-control" id="pwd" name="password" required>
    </div>
    <button type="submit" class="btn btn-primary">登录</button>
    <button type="button" class="btn btn-link"><a href="{{ url_for('auth.signup') }}">注册</a></button>
  </form>
</div>
</body>
</html>

app/templates/signup.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
</head>
<body>
<div class="container">
  <h2 class="text-center">注册</h2>
  <form action="{{ url_for('auth.signup') }}" method="post">
    <div class="form-group">
      <label for="username">用户名:</label>
      <input type="text" class="form-control" id="username" name="username" required>
    </div>
    <div class="form-group">
      <label for="email">邮箱:</label>
      <input type="email" class="form-control" id="email" name="email" required>
    </div>
    <div class="form-group">
      <label for="pwd">密码:</label>
      <input type="password" class="form-control" id="pwd" name="password" required>
    </div>
    <div class="form-group">
      <label for="cpwd">确认密码:</label>
      <input type="password" class="form-control" id="cpwd" name="confirm_password" required>
    </div>
    <button type="submit" class="btn btn-primary">注册</button>
    <button type="button" class="btn btn-link"><a href="{{ url_for('auth.login') }}">已有账户？登录</a></button>
  </form>
</div>
</body>
</html>